### ISSUE TITLE
ionic install not working

### ISSUE THREAD

**Issue by narf** [appodeal/appodeal-cordova-plugin#39]
When trying to insqtall with ionic:
```
ionic cordova plugin add https://github.com/appodeal/appodeal-cordova-plugin.git
```

I have these errors:

```
[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add
        https://github.com/appodeal/appodeal-cordova-plugin.git --sav... (exit code 1):

        Error: Failed to fetch plugin https://github.com/appodeal/appodeal-cordova-plugin.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! code 128
        npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
        npm ERR! fatal: 'submodule' appears to be a git command, but we were not
        npm ERR! able to execute it. Maybe git-submodule is broken?
        npm ERR!

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Narf\AppData\Roaming\npm-cache\_logs\2017-07-16T09_59_13_916Z-debug.log
```

**Comment by rashnk** [comment]
any solution  ?

**Comment by narf** [comment]
Oh, sorry for the late answer.
The solution was to add the plugin with 
`cordova plugin add https://github.com/appodeal/appodeal-cordova-plugin.git#cordova2`

But I encountered other problems and the project is on a hold right now.

**Comment by rashnk** [comment]
cordova plugin add com.appodeal.plugin

**Comment by lahed** [comment]
dont work video rewarded callback =(

**Comment by Tamplier** [comment]
@lahed, please provide us more details about the problem.
Is that reproducible for both platforms (Android and iOS)?
What version (or what branch) of the plugin do you use (give us a link please)?
Can you share some parts of your code (Appodeal related)?
A log will be useful too (or you can send us your apk with description).

**Comment by mifkys** [comment]
I created issue in ionic-cli repository with some information: https://github.com/ionic-team/ionic-cli/issues/2836 Maybe this issue cause next other issue: https://github.com/ionic-team/ionic-native/issues/2065 Need help!

**Comment by mifkys** [comment]
https://github.com/appodeal/appodeal-cordova-maxdex-plugin.git also fails to install on android platform:

`ionic cordova plugin add https://github.com/appodeal/appodeal-cordova-maxdex-plugin.git`

> > cordova plugin add https://github.com/appodeal/appodeal-cordova-maxdex-plugin.git --save
> Error: Failed to fetch plugin https://github.com/appodeal/appodeal-cordova-maxdex-plugin.git via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: cmd: Command failed with exit code 1 Error output:
> npm ERR! git submodule -q update --init --recursive: fatal: 'submodule' appears to be a git command, but we were not
> npm ERR! git submodule -q update --init --recursive: able to execute it. Maybe git-submodule is broken?
> npm ERR! git submodule -q update --init --recursive:
> npm ERR! Windows_NT 10.0.16299
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/appodeal/appodeal-cordova-maxdex-plugin.git" "--save"
> npm ERR! node v6.5.0
> npm ERR! npm  v3.10.3
> npm ERR! code 128
> 
> npm ERR! Command failed: git -c core.longpaths=true submodule -q update --init --recursive
> npm ERR! fatal: 'submodule' appears to be a git command, but we were not
> npm ERR! able to execute it. Maybe git-submodule is broken?
> npm ERR!
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\apps\history\node_modules\npm-debug.log
> 
> [ERROR] An error occurred while running cordova plugin add
>         https://github.com/appodeal/appodeal-cordova-maxdex-plugin.gi... (exit code 1).

**Comment by Tamplier** [comment]
@mifkys, hi!
Try to update npm and cordova,  after that add --nofetch parameter to plugin add command.

**Comment by mifkys** [comment]
ionic cut --nofetch param so problem still exists.

**Comment by Tamplier** [comment]
@mifkys try to update your npm, node, cordova and git (most important, as far according to your log, the source of the problem is in "submodule" git command).
Also, can you share log from  C:\apps\history\node_modules\npm-debug.log?

**Comment by mifkys** [comment]
updated special to latest versions:
npm 5.5.1
node 8.9.0
cordova 7.0.1
git 2.15.0.windows.1

Error is the same:

> Error: Failed to fetch plugin https://github.com/appodeal/appodeal-cordova-plugin.git via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: cmd: Command failed with exit code 1 Error output:
> npm ERR! code 128
> npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
> npm ERR! fatal: 'submodule' appears to be a git command, but we were not
> npm ERR! able to execute it. Maybe git-submodule is broken?
> npm ERR!
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2017-11-07T06_53_47_034Z-debug.log
> 
> [ERROR] An error occurred while running cordova plugin add https://github.com/appodeal/appodeal-cordova-plugin.git
>         --sav... (exit code 1).


**npm-debug**:
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   'https://github.com/appodeal/appodeal-cordova-plugin.git',
> 1 verbose cli   '--save' ]
> 2 info using npm@5.5.1
> 3 info using node@v8.9.0
> 4 verbose npm-session 1dd2b7590a9cd08a
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 silly fetchPackageMetaData error for git+https://github.com/appodeal/appodeal-cordova-plugin.git Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
> 7 silly fetchPackageMetaData fatal: 'submodule' appears to be a git command, but we were not
> 7 silly fetchPackageMetaData able to execute it. Maybe git-submodule is broken?
> 8 verbose stack Error: Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
> 8 verbose stack fatal: 'submodule' appears to be a git command, but we were not
> 8 verbose stack able to execute it. Maybe git-submodule is broken?
> 8 verbose stack
> 8 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
> 8 verbose stack     at emitTwo (events.js:126:13)
> 8 verbose stack     at ChildProcess.emit (events.js:214:7)
> 8 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 9 verbose cwd C:\apps\history\node_modules
> 10 verbose Windows_NT 10.0.16299
> 11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/appodeal/appodeal-cordova-plugin.git" "--save"
> 12 verbose node v8.9.0
> 13 verbose npm  v5.5.1
> 14 error code 128
> 15 error Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
> 15 error fatal: 'submodule' appears to be a git command, but we were not
> 15 error able to execute it. Maybe git-submodule is broken?
> 16 verbose exit [ 1, true ]

**Comment by Tamplier** [comment]
It's very strange. Can you run `submodule update --init --recursive` in your project folder and share output?

**Comment by mifkys** [comment]
`submodule update --init --recursive` return `Not recognized as internal or external command` in cmd

**Comment by Tamplier** [comment]
Not a `submodule ...`, correct call is `git submodule ...`

**Comment by mifkys** [comment]
No return after this command

**Comment by KeizrulAzfar** [comment]
I also got same error like @mifkys , suggestion for any solution?

**Comment by oguzhansevim** [comment]
I got same error like @mifkys @KeizrulAzfar, any solution?

**Comment by oguzhansevim** [comment]
Hi guys! @mifkys , @KeizrulAzfar if you wait the some minutes plugin can be successfully installed!

**Comment by lahed** [comment]
does not work = (

**Comment by Tamplier** [comment]
@lahed can you provide some details?

**Comment by Tamplier** [comment]
@mifkys @KeizrulAzfar can you confirm that oguzhansevim's solution works for you?

**Comment by mifkys** [comment]
Nope. After 5-10min wait:

> Error: Failed to fetch plugin https://github.com/appodeal/appodeal-cordova-plugin.git via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: cmd: Command failed with exit code 1 Error output:
> npm ERR! code 1
> npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
> npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
> npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
> npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
> npm ERR!
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\m\AppData\Roaming\npm-cache\_logs\2017-11-27T11_14_46_313Z-debug.log
> 
> [ERROR] An error occurred while running cordova plugin add https://github.com/appodeal/appodeal-cordova-plugin.git
>         --sav... (exit code 1).

**Comment by oguzhansevim** [comment]
Did you try create a new project and add plugin ? @mifkys

**Comment by mifkys** [comment]
Yes, just created test2 project, added android platform and execute ionic cordova command. Same error

**Comment by Tamplier** [comment]
@mifkys try another way to disable fetching:
`cordova config set fetch false`
If it won't help, run `cordova plugin add ...` (without ionic) and send us your output.

**Comment by wo-github** [comment]
Same problem here:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'PATH\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/appodeal/appodeal-cordova-plugin.git',
1 verbose cli   '--production',
1 verbose cli   '--save' ]
2 info using npm@5.6.0
3 info using node@v6.9.1
4 verbose npm-session 20eaad39b96b99fb
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/appodeal/appodeal-cordova-plugin.git Command failed: C:\Program Files (x86)\SmartGit\git\cmd\git.EXE submodule update -q --init --recursive
7 silly fetchPackageMetaData fatal: 'submodule' appears to be a git command, but we were not
7 silly fetchPackageMetaData able to execute it. Maybe git-submodule is broken?
8 verbose stack Error: Command failed: C:\Program Files (x86)\SmartGit\git\cmd\git.EXE submodule update -q --init --recursive
8 verbose stack fatal: 'submodule' appears to be a git command, but we were not
8 verbose stack able to execute it. Maybe git-submodule is broken?
8 verbose stack
8 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
8 verbose stack     at emitTwo (events.js:106:13)
8 verbose stack     at ChildProcess.emit (events.js:191:7)
8 verbose stack     at maybeClose (internal/child_process.js:877:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
9 verbose cwd PATH\Documents\Deploy\ionic2
10 verbose Windows_NT 10.0.16299
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "PATH\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/appodeal/appodeal-cordova-plugin.git" "--production" "--save"
12 verbose node v6.9.1
13 verbose npm  v5.6.0
14 error code 128
15 error Command failed: C:\Program Files (x86)\SmartGit\git\cmd\git.EXE submodule update -q --init --recursive
15 error fatal: 'submodule' appears to be a git command, but we were not
15 error able to execute it. Maybe git-submodule is broken?
16 verbose exit [ 1, true ]

**Comment by Tamplier** [comment]
@wo-github 
I can't reproduce this. I have the following versions of required software:
Ionic 3.19.1
cordova 8.0.0
npm 5.6.0
node 6.11.3
git 2.11.0.windows.3
If you have older versions, try to update your environment. 
Also, ensure that you have enough space (check drive C too), clean your npm cache and try to run command line as administrator. 
P.S. Appodeal plugin has big size due to really big amount of networks, so you need to wait for about 20-30 minutes while installation will be finished.
