### ISSUE TITLE
Problems running the command ionic cordova run android

### ISSUE THREAD

**Issue by diegoestacho999** [appodeal/appodeal-cordova-plugin#68]
I'm having this error below, when trying to run the project on the emulator / cell for testing, does anyone know how to solve it?

* Where:
Build file 'C:\Users\Diego\Desktop\appodeal-testar\platforms\android\com.appodeal.plugin\starter-adcolony\build.gradle' line: 48

* What went wrong:
A problem occurred evaluating project ':com.appodeal.plugin:starter-adcolony'.
> Could not get unknown property 'cdvCompileSdkVersion' for object of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Picked up _JAVA_OPTIONS: -Xmx512M
    at ChildProcess.whenDone (C:\Users\Diego\Desktop\appodeal-testar\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:4088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rmatosaw** [comment]
Have you solved the problem?
We had the same problem today.
Solved doing this:
1) execute ionic cordova prepare
2) remove platform and install again
3) adjust firebase (something went wrong after the gradle update)

After 8 hours trying different solutions. Alive!
